#!/bin/bash

set -e

IMAGE=vol-cleanup
BUILD=${IMAGE}-build
BIN_TARGET=/usr/bin/vol-cleanup

cd $(dirname $0)/..

mkdir -p ./dist
docker build -t $BUILD .
docker run -v $(pwd)/dist:/target $BUILD cp ${BIN_TARGET} /target
